owner: tictactrip
repo: status

sites:
  - name: Website
    url: https://www.tictactrip.eu
  - name: Blog
    url: https://www.tictactrip.eu/blog
  - name: API
    url: https://api.tictactrip.eu/apistatus/maintenance 

assignees:
  - rimiti
  - simobain
  - alexfrst
  - jean-philippeBuffon

status-website:
  cname: status.tictactrip.eu
  logoUrl: https://svgshare.com/i/nS3.svg
  name: Tictactrip
  introTitle: "**Tictactrip** service status."
  introMessage: Status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
